use proc_macro2::TokenStream;
use quote::quote;
use syn::{ItemFn, Ident};

/// Parse `#[action(name = "save-contact")]` and generate a constant.
///
/// Given `#[action(name = "save-contact")] fn save_contact(...)`,
/// generates `pub const SAVE_CONTACT: &str = "save-contact";`
/// alongside the original function.
pub fn action_impl(attr: TokenStream, item: TokenStream) -> TokenStream {
    let input: ItemFn = match syn::parse2(item) {
        Ok(v) => v,
        Err(e) => return e.to_compile_error(),
    };

    let name_value = match parse_name_attr(attr) {
        Ok(v) => v,
        Err(e) => return e.to_compile_error(),
    };

    // Convert "save-contact" -> "SAVE_CONTACT"
    let const_name_str = name_value.replace('-', "_").to_uppercase();
    let const_ident = Ident::new(&const_name_str, proc_macro2::Span::call_site());

    quote! {
        /// Action name constant generated by `#[action]`.
        pub const #const_ident: &str = #name_value;

        #input
    }
}

/// Parse `name = "value"` from the attribute token stream.
fn parse_name_attr(attr: TokenStream) -> Result<String, syn::Error> {
    let meta: syn::MetaNameValue = syn::parse2(attr)?;
    if !meta.path.is_ident("name") {
        return Err(syn::Error::new_spanned(
            meta.path,
            "expected `name = \"...\"`",
        ));
    }
    if let syn::Expr::Lit(syn::ExprLit {
        lit: syn::Lit::Str(ref s),
        ..
    }) = meta.value
    {
        Ok(s.value())
    } else {
        Err(syn::Error::new_spanned(
            meta.value,
            "expected a string literal for `name`",
        ))
    }
}
