use proc_macro2::TokenStream;
use quote::quote;
use syn::{ItemFn, Ident};

/// Parse `#[requires(authenticated)]` or `#[requires(role = "admin")]` and
/// generate a companion `{FN_NAME}_AUTH` constant with `AuthRequirement` value.
pub fn requires_impl(attr: TokenStream, item: TokenStream) -> TokenStream {
    let input: ItemFn = match syn::parse2(item) {
        Ok(v) => v,
        Err(e) => return e.to_compile_error(),
    };

    let requirement = match parse_requirement(attr) {
        Ok(v) => v,
        Err(e) => return e.to_compile_error(),
    };

    let fn_name = &input.sig.ident;
    let const_name_str = format!("{}_AUTH", fn_name.to_string().to_uppercase());
    let const_ident = Ident::new(&const_name_str, fn_name.span());

    let auth_value = match requirement {
        Requirement::Authenticated => {
            quote! { ::marionette_protocol::AuthRequirement::Authenticated }
        }
        Requirement::Role(role) => {
            quote! { ::marionette_protocol::AuthRequirement::Role(#role) }
        }
    };

    quote! {
        /// Authorization requirement generated by `#[requires]`.
        pub const #const_ident: ::marionette_protocol::AuthRequirement = #auth_value;

        #input
    }
}

enum Requirement {
    Authenticated,
    Role(String),
}

/// Parse either `authenticated` or `role = "admin"`.
fn parse_requirement(attr: TokenStream) -> Result<Requirement, syn::Error> {
    // Try parsing as a single ident first (e.g., `authenticated`)
    if let Ok(ident) = syn::parse2::<Ident>(attr.clone()) {
        if ident == "authenticated" {
            return Ok(Requirement::Authenticated);
        }
        return Err(syn::Error::new_spanned(
            ident,
            "expected `authenticated` or `role = \"...\"`",
        ));
    }

    // Try parsing as name = value (e.g., `role = "admin"`)
    let meta: syn::MetaNameValue = syn::parse2(attr)?;
    if !meta.path.is_ident("role") {
        return Err(syn::Error::new_spanned(
            meta.path,
            "expected `authenticated` or `role = \"...\"`",
        ));
    }
    if let syn::Expr::Lit(syn::ExprLit {
        lit: syn::Lit::Str(ref s),
        ..
    }) = meta.value
    {
        Ok(Requirement::Role(s.value()))
    } else {
        Err(syn::Error::new_spanned(
            meta.value,
            "expected a string literal for `role`",
        ))
    }
}
