[package]
name = "marionette"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
marionette-protocol = { path = "../marionette-protocol" }
marionette-macros = { path = "../marionette-macros" }
serde.workspace = true
serde_json.workspace = true
axum.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true
sea-orm.workspace = true
sea-orm-migration.workspace = true
axum-extra.workspace = true
chrono.workspace = true
futures.workspace = true
linkme = { workspace = true, optional = true }

[dev-dependencies]
sea-orm = { workspace = true, features = ["mock"] }
tokio-tungstenite.workspace = true

[features]
gallery = ["dep:linkme"]
